# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: 最不贴近高考的高中物理课程
site_url: https://example.com/mysite
theme:
  name: material
  language: zh
  palette:
    scheme: default
    primary: indigo
  font:
    text: Noto Sans SC
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js